external-controller: 127.0.0.1:9090
mixed-port: 7890
proxies:
- alterId: 2
  cipher: auto
  name: node_0
  network: tcp
  port: 30807
  server: v10.hdacd.com
  tls: false
  type: vmess
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  ws-opts: null
proxy-groups:
- name: GLOBAL
  proxies:
  - node_0
  type: select
