external-controller: 127.0.0.1:9090
log-level: silent
mixed-port: 7890
mode: global
proxies:
- name: N_0000
  port: 443
  server: null
  skip-cert-verify: true
  udp: true
- cipher: none
  name: N_0001
  password: 3e96ef7d-8637-42c2-ac73-75182196e755
  port: 443
  server: cdns.doon.eu.org
  skip-cert-verify: true
  type: ss
  udp: true
- cipher: none
  name: N_0002
  password: 3e96ef7d-8637-42c2-ac73-75182196e755
  port: 443
  server: cf.008500.xyz
  skip-cert-verify: true
  type: ss
  udp: true
- cipher: none
  name: N_0003
  password: 3e96ef7d-8637-42c2-ac73-75182196e755
  port: 443
  server: cf.090227.xyz
  skip-cert-verify: true
  type: ss
  udp: true
- cipher: none
  name: N_0004
  password: 3e96ef7d-8637-42c2-ac73-75182196e755
  port: 443
  server: cf.130519.xyz
  skip-cert-verify: true
  type: ss
  udp: true
- cipher: none
  name: N_0005
  password: 3e96ef7d-8637-42c2-ac73-75182196e755
  port: 443
  server: cf.877774.xyz
  skip-cert-verify: true
  type: ss
  udp: true
- cipher: none
  name: N_0006
  password: 3e96ef7d-8637-42c2-ac73-75182196e755
  port: 443
  server: cf.zhetengsha.eu.org
  skip-cert-verify: true
  type: ss
  udp: true
- cipher: none
  name: N_0007
  password: 3e96ef7d-8637-42c2-ac73-75182196e755
  port: 443
  server: mfa.gov.ua
  skip-cert-verify: true
  type: ss
  udp: true
- cipher: none
  name: N_0008
  password: 3e96ef7d-8637-42c2-ac73-75182196e755
  port: 443
  server: saas.sin.fan
  skip-cert-verify: true
  type: ss
  udp: true
- cipher: none
  name: N_0009
  password: 3e96ef7d-8637-42c2-ac73-75182196e755
  port: 443
  server: store.ubi.com
  skip-cert-verify: true
  type: ss
  udp: true
- cipher: none
  name: N_0010
  password: 3e96ef7d-8637-42c2-ac73-75182196e755
  port: 443
  server: sub.danfeng.eu.org
  skip-cert-verify: true
  type: ss
  udp: true
- name: N_0011
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55011
  server: c80c993c-e6d4-548c-88c0-c4893b3d3d4d.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0012
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55012
  server: c80c993c-e6d4-548c-88c0-c4893b3d3d4d.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0013
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55013
  server: c80c993c-e6d4-548c-88c0-c4893b3d3d4d.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0014
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55014
  server: c80c993c-e6d4-548c-88c0-c4893b3d3d4d.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0015
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55021
  server: c80c993c-e6d4-548c-88c0-c4893b3d3d4d.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0016
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55022
  server: c80c993c-e6d4-548c-88c0-c4893b3d3d4d.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0017
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55023
  server: c80c993c-e6d4-548c-88c0-c4893b3d3d4d.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0018
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55024
  server: c80c993c-e6d4-548c-88c0-c4893b3d3d4d.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0019
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55031
  server: c80c993c-e6d4-548c-88c0-c4893b3d3d4d.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0020
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55032
  server: c80c993c-e6d4-548c-88c0-c4893b3d3d4d.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0021
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55033
  server: c80c993c-e6d4-548c-88c0-c4893b3d3d4d.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0022
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55034
  server: c80c993c-e6d4-548c-88c0-c4893b3d3d4d.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0023
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55041
  server: c80c993c-e6d4-548c-88c0-c4893b3d3d4d.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0024
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55042
  server: c80c993c-e6d4-548c-88c0-c4893b3d3d4d.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0025
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55043
  server: c80c993c-e6d4-548c-88c0-c4893b3d3d4d.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0026
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55044
  server: c80c993c-e6d4-548c-88c0-c4893b3d3d4d.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0027
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55051
  server: c80c993c-e6d4-548c-88c0-c4893b3d3d4d.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0028
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55052
  server: c80c993c-e6d4-548c-88c0-c4893b3d3d4d.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0029
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55053
  server: c80c993c-e6d4-548c-88c0-c4893b3d3d4d.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0030
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55054
  server: c80c993c-e6d4-548c-88c0-c4893b3d3d4d.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0031
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55011
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0032
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55011
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0033
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55011
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0034
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55011
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0035
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55012
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0036
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55013
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0037
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55014
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0038
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55021
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0039
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55022
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0040
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55023
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0041
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55024
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0042
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55031
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0043
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55032
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0044
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55033
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0045
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55034
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0046
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55041
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0047
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55042
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0048
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55043
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0049
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55044
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0050
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55051
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0051
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55052
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0052
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55053
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
- name: N_0053
  password: da6f49ae-b0dd-4527-b993-ae6ec688000c
  port: 55054
  server: f4d7f1c2f3b80976a5e2c1d4b3f0f321.358.onl
  skip-cert-verify: true
  sni: www.h3yun.com
  tls: true
  type: trojan
  udp: true
