name: speed_test

on:
  workflow_dispatch: # 支持手动运行
  push:
    paths:
      - 'speed_test.py'
      - '.github/workflows/speed_test.yml'
      - 'nodes_list.txt'

jobs:
  test_and_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests pyyaml pytz

      - name: Run Speed Test
        run: |
         
          python speed_test.py

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add nodes_list_fast.txt README.md YYYY/MM/*.txt
          
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto: Update Speed Test Report $(date +'%Y-%m-%d %H:%M')"
          git push
