name: speed_test

on:
  workflow_dispatch:
  push:
    paths:
      - 'speed_test.py'
      - '.github/workflows/speed_test.yml'
      - 'nodes_list.txt'

jobs:
  run-speed-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyyaml requests pytz

      - name: Run Speed Test Script
        run: python speed_test.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add nodes_list_fast.txt README.md 20*/*/*.txt
          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "Auto: Update fast nodes with speed tag"
            git push
          fi
